# -*- coding: utf-8 -*-
"""MNIST_handwritten.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STpWD8tbFeyRLtodQ-E3VrPdv2Bn5gP9

## MNIST HANDWRITTEN DIGIT CLASSIFIER

importing the predefined
"""

import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

"""Loading  the dataset

"""

mnist = fetch_openml('mnist_784', version=1)

"""Normalising the data
(divided by 255 as the pixels of the images are 255 max)

"""

X = mnist.data.astype('float32') / 255.0
y = mnist.target.astype('int')

"""The data is splitted and knn is initialised to make predictions."""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier(n_neighbors=5)


knn.fit(X_train, y_train)


y_pred = knn.predict(X_test)

"""Calculating the accuracy."""

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

"""showing some sample predictions with image

"""

test_images = np.array(test_images)


for test in test_images:
    im = test.reshape((28, 28))
    plt.figure()
    plt.imshow(im, cmap='gray')
    plt.show()
    prediction = knn.predict(test.reshape(1, -1))
    print("Predicted Label:", prediction)

